# Generated by Django 3.0.5 on 2021-03-30 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Use up to two decimals', max_digits=3, verbose_name='Quantity')),
                ('ingredients', models.TextField(help_text='One ingredient per line', verbose_name='Ingredients')),
                ('preparation', models.TextField(verbose_name='Preparation')),
                ('time_for_preparation', models.DurationField(blank=True, help_text='In minutes', null=True, verbose_name='Preparation time')),
                ('number_of_portions', models.PositiveIntegerField(verbose_name='Number of portions')),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_updated', models.DateTimeField(editable=False)),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'easy'), (2, 'normal'), (3, 'hard')], default=2, verbose_name='Difficulty')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(to='recipes.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-date_created'],
            },
        ),
    ]
