# Generated by Django 3.0.5 on 2021-04-16 11:59

from django.db import migrations, models
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210411_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity_fraction',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=4, default=0, help_text='Optional fraction', limit_denominator=None, max_digits=4, null=0, verbose_name='Fraction'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity_integer',
            field=models.PositiveSmallIntegerField(default=0, help_text='Only positive whole numbers', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
