# Generated by Django 3.0.5 on 2021-04-16 12:06

from django.db import migrations, models
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210416_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity_fraction',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=4, help_text='Optional fraction', limit_denominator=None, max_digits=4, null=True, verbose_name='Fraction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_integer',
            field=models.PositiveSmallIntegerField(help_text='Only positive whole numbers', verbose_name='Quantity'),
        ),
    ]
