# Generated by Django 3.0.5 on 2021-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210418_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity_integer',
            field=models.PositiveSmallIntegerField(help_text='Only positive whole numbers', null=True, verbose_name='Quantity'),
        ),
    ]
