# Generated by Django 3.0.5 on 2021-04-19 05:52

from django.db import migrations
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210419_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity_fraction',
            field=djfractions.models.fields.DecimalFractionField(blank=True, coerce_thirds=True, decimal_places=4, help_text='Optional fraction', limit_denominator=None, max_digits=4, verbose_name='Fraction'),
        ),
    ]
